server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /como-funciona/ { return 301 /como-funciona; }
    location = /ocorrencias/ { return 301 /ocorrencias; }
    location = /representantes/ { return 301 /representantes; }
    location = /planos/ { return 301 /planos; }
    location = /sobre/ { return 301 /sobre; }

    location / {
        try_files $uri $uri.html /index.html;
    }
}
