#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

fail() {
  echo "ERRO: $*" >&2
  exit 1
}

CONTRACTS="$ROOT/apps/api/src/CidadeEmDia.Application/Occurrences/IOccurrenceGeoSearchService.cs"
SERVICE="$ROOT/apps/api/src/CidadeEmDia.Infrastructure/Occurrences/OccurrenceGeoSearchService.cs"
GEO_ENDPOINTS="$ROOT/apps/api/src/CidadeEmDia.Api/Endpoints/OccurrenceGeoEndpoints.cs"
CREATE_ENDPOINTS="$ROOT/apps/api/src/CidadeEmDia.Api/Endpoints/OccurrenceEndpoints.cs"
CREATE_SERVICE="$ROOT/apps/api/src/CidadeEmDia.Infrastructure/Occurrences/OccurrenceCreationService.cs"
MAIN="$ROOT/apps/web/src/main.tsx"
TOAST="$ROOT/apps/web/src/components/toast.ts"
TOAST_VIEWPORT="$ROOT/apps/web/src/components/ToastViewport.tsx"
TOAST_CSS="$ROOT/apps/web/src/styles/toast.css"
HOME_SERVICE="$ROOT/apps/web/src/modules/home/homeService.ts"
HOME="$ROOT/apps/web/src/modules/home/PublicHome.tsx"
CENTER="$ROOT/apps/web/src/modules/occurrences/OccurrenceCenter.tsx"
LOCATION="$ROOT/apps/web/src/modules/occurrences/OccurrenceLocationPicker.tsx"
CARD="$ROOT/apps/web/src/modules/occurrences/PublicOccurrenceCard.tsx"
CARD_CSS="$ROOT/apps/web/src/modules/occurrences/public-occurrence-card.css"
REQUIRED_LABEL_CSS="$ROOT/apps/web/src/modules/occurrences/occurrence-required-labels.css"
LIST="$ROOT/apps/web/src/modules/occurrences/PublicOccurrences.tsx"
MODAL="$ROOT/apps/web/src/modules/occurrences/PublicOccurrenceDetailsModal.tsx"
SUPPORT="$ROOT/apps/web/src/modules/occurrences/OccurrenceSupportButton.tsx"
CSS="$ROOT/apps/web/src/modules/occurrences/public-occurrences.css"

for file in \
  "$CONTRACTS" "$SERVICE" "$GEO_ENDPOINTS" "$CREATE_ENDPOINTS" "$CREATE_SERVICE" \
  "$MAIN" "$TOAST" "$TOAST_VIEWPORT" "$TOAST_CSS" "$HOME_SERVICE" "$HOME" "$CENTER" "$LOCATION" \
  "$CARD" "$CARD_CSS" "$REQUIRED_LABEL_CSS" "$LIST" "$MODAL" "$SUPPORT" "$CSS"; do
  test -f "$file" || fail "arquivo ausente: $file"
done

grep -q 'PublicOccurrenceMediaItem' "$CONTRACTS" || fail "contrato público de mídia ausente"
grep -q 'CoverMedia' "$CONTRACTS" || fail "capa pública ausente do contrato"
grep -q 'SupportCount' "$CONTRACTS" || fail "contagem pública de apoio ausente do contrato"
grep -q 'ExternalProtocolNumber' "$CONTRACTS" || fail "protocolo público ausente do contrato"
grep -q 'GetPublicDetailsAsync' "$CONTRACTS" || fail "contrato de detalhe público ausente"
grep -q 'ContentType.StartsWith("image/")' "$SERVICE" || fail "capa não está limitada a imagem"
grep -q 'media.Status == OccurrenceMediaStatus.Ready' "$SERVICE" || fail "mídia pública não está limitada a READY"
grep -q 'OrderBy(media => media.CreatedAt)' "$SERVICE" || fail "ordem original de upload não está preservada"
grep -q 'CreateReadUrl' "$SERVICE" || fail "mídia pública não usa URL assinada"
grep -q 'OccurrenceSupports' "$SERVICE" || fail "listagem pública não agrega contagem de apoio"
grep -q '/public/occurrences/{occurrenceId:guid}' "$GEO_ENDPOINTS" || fail "endpoint de detalhe público ausente"

grep -q 'Guid MasterUserId' "$CREATE_ENDPOINTS" || fail "criação não exige Master"
grep -q 'Street is required' "$CREATE_ENDPOINTS" || fail "rua não é validada no backend"
grep -q 'Street number is required' "$CREATE_ENDPOINTS" || fail "número não é validado no backend"
grep -q 'Neighborhood is required' "$CREATE_ENDPOINTS" || fail "bairro não é validado no backend"
grep -q 'City is required' "$CREATE_ENDPOINTS" || fail "cidade não é validada no backend"
grep -q 'External protocol number is required' "$CREATE_ENDPOINTS" || fail "protocolo não é obrigatório no backend"
grep -q 'photo_required' "$CREATE_SERVICE" || fail "foto não é obrigatória na criação"
grep -q 'AddMasterTarget(masterUserId' "$CREATE_SERVICE" || fail "target inicial para Master não é criado"
grep -q 'BeginTransactionAsync' "$CREATE_SERVICE" || fail "criação de ocorrência/target/mídia não é transacional"

grep -q 'listEligibleMasters' "$CENTER" || fail "formulário não lista contas Master"
grep -q 'masterUserId' "$CENTER" || fail "formulário não envia Master selecionada"
grep -q "files.some((file) => file.type.startsWith('image/'))" "$CENTER" || fail "formulário não exige pelo menos uma foto"
grep -q 'Informe o número do protocolo' "$CENTER" || fail "formulário não exige protocolo"
grep -q 'Informe a rua' "$CENTER" || fail "formulário não valida rua"
grep -q 'Informe o número' "$CENTER" || fail "formulário não valida número"
grep -q 'Informe o bairro' "$CENTER" || fail "formulário não valida bairro"
grep -q 'Informe a cidade' "$CENTER" || fail "formulário não valida cidade"
grep -q 'Buscar no mapa' "$LOCATION" || fail "endereço digitado não pode ser refletido no mapa"
grep -q 'street_number' "$LOCATION" || fail "PIN não preenche número do endereço"
grep -q "getAddressComponent(components, 'route')" "$LOCATION" || fail "PIN não preenche rua"
grep -q "getAddressComponent(components, 'locality')" "$LOCATION" || fail "PIN não preenche cidade"
grep -q "occurrence-required-labels.css" "$MAIN" || fail "layout dos títulos obrigatórios não está carregado"
grep -q 'flex-wrap: wrap' "$REQUIRED_LABEL_CSS" || fail "título e asterisco obrigatórios não permanecem na mesma linha"
grep -q 'occurrence-required-marker' "$REQUIRED_LABEL_CSS" || fail "marcador obrigatório não possui proteção de layout"
grep -q 'occurrence-form__paired-field' "$REQUIRED_LABEL_CSS" || fail "campos pareados não possuem alinhamento compartilhado"

PROTOCOL_LINE="$(grep -n 'Número do protocolo <span className="occurrence-required-marker"' "$CENTER" | head -n1 | cut -d: -f1)"
CATEGORY_LINE="$(grep -n 'Categoria <span className="occurrence-required-marker"' "$CENTER" | head -n1 | cut -d: -f1)"
MASTER_LINE="$(grep -n 'Conta Master <span className="occurrence-required-marker"' "$CENTER" | head -n1 | cut -d: -f1)"
TITLE_LINE="$(grep -n 'Título <span className="occurrence-required-marker"' "$CENTER" | head -n1 | cut -d: -f1)"
DESCRIPTION_LINE="$(grep -n '^                Descrição$' "$CENTER" | head -n1 | cut -d: -f1)"

test -n "$PROTOCOL_LINE" && test -n "$CATEGORY_LINE" && test -n "$MASTER_LINE" && test -n "$TITLE_LINE" && test -n "$DESCRIPTION_LINE" \
  || fail "não foi possível validar a ordem semântica do formulário"
test "$PROTOCOL_LINE" -lt "$CATEGORY_LINE" || fail "protocolo não é o primeiro campo"
test "$CATEGORY_LINE" -lt "$MASTER_LINE" || fail "categoria e conta Master não estão pareadas na ordem esperada"
test "$MASTER_LINE" -lt "$TITLE_LINE" || fail "título deveria vir após categoria/conta Master"
test "$TITLE_LINE" -lt "$DESCRIPTION_LINE" || fail "descrição deveria vir após o título"
test "$(grep -c 'className="occurrence-form__paired-field"' "$CENTER")" -eq 2 || fail "categoria e conta Master devem ser os dois campos pareados"
grep -q 'occurrence-form__protocol-field occurrence-form__full' "$CENTER" || fail "protocolo não ocupa linha isolada"
grep -q 'occurrence-form__title-field occurrence-form__full' "$CENTER" || fail "título não ocupa linha isolada"

grep -q 'ToastViewport' "$MAIN" || fail "viewport global de toast não está montado"
grep -q 'installNativeAlertToastBridge' "$MAIN" || fail "bridge global de alert para toast não está instalado"
grep -q "import './styles/toast.css'" "$MAIN" || fail "estilos globais de toast não estão carregados"
grep -q 'aria-live="polite"' "$TOAST_VIEWPORT" || fail "toast não possui região aria-live"
grep -q "toast.info('Entre ou crie sua conta para apoiar esta ocorrência.')" "$SUPPORT" || fail "apoio anônimo não usa toast"
if grep -RInE '(window\.)?alert[[:space:]]*\(' "$ROOT/apps/web/src" --include='*.ts' --include='*.tsx' >/dev/null; then
  fail "ainda existe chamada de alert nativo no frontend"
fi

grep -q 'getPublicOccurrenceDetails' "$HOME_SERVICE" || fail "client de detalhe público ausente"
grep -q 'supportOccurrence' "$HOME_SERVICE" || fail "client de apoio autenticado ausente"
grep -q 'occurrence.coverMedia.readUrl' "$CARD" || fail "card não usa primeira foto como capa"
grep -q 'Protocolo {occurrence.externalProtocolNumber}' "$CARD" || fail "protocolo não está destacado no card público"
grep -q 'OccurrenceSupportButton' "$CARD" || fail "card público não exibe botão de apoio"
grep -q "import './public-occurrence-card.css'" "$CARD" || fail "card público não carrega layout próprio"
grep -q 'OccurrenceSupportButton' "$MODAL" || fail "detalhe público não exibe botão de apoio"
grep -q "public-occurrence-support__icon.*↑" "$SUPPORT" || fail "apoio não usa seta para cima"
grep -q 'initialCount' "$SUPPORT" || fail "botão de apoio não exibe contagem pública"
grep -q 'getAccessToken' "$SUPPORT" || fail "botão de apoio não diferencia sessão autenticada"
grep -q 'object-fit: cover' "$CSS" || fail "foto de capa não preenche a área disponível"
grep -q 'public-occurrence-support' "$CSS" || fail "estilo do apoio público ausente"
grep -q 'public-home__occurrence-main .public-occurrence-support--card' "$CARD_CSS" || fail "apoio não está ancorado dentro do conteúdo principal do card"
grep -q 'position: absolute' "$CARD_CSS" || fail "apoio do card não usa posicionamento no canto superior direito"
grep -q 'top: 10px' "$CARD_CSS" || fail "apoio do card não respeita margem superior interna"
grep -q 'right: 10px' "$CARD_CSS" || fail "apoio do card não respeita margem direita interna"
grep -q 'padding: 10px 78px 10px 0' "$CARD_CSS" || fail "conteúdo principal não reserva espaço para o apoio"
grep -q 'data-occurrence-id={occurrence.id}' "$CARD" || fail "card público não possui seletor estável para E2E"
grep -q 'aria-label={interactive ? `Abrir ocorrência ${occurrence.publicCode}: ${occurrence.title}`' "$CARD" || fail "linha da ocorrência não possui nome acessível"
grep -q 'onClick={onOpen ? () => onOpen(occurrence) : undefined}' "$CARD" || fail "linha inteira da ocorrência não permanece clicável"
grep -q 'tabIndex={interactive ? 0 : undefined}' "$CARD" || fail "linha clicável não permanece acessível por teclado"
if grep -q 'public-occurrence-open-button' "$CARD" || grep -q 'public-occurrence-open-button' "$CARD_CSS"; then
  fail "botão Abrir não deve existir no card público"
fi
if grep -q 'role={interactive ? .button.' "$CARD"; then
  fail "card público não pode ser um botão lógico contendo o botão de apoio"
fi
grep -q 'PublicOccurrenceDetailsModal' "$LIST" || fail "listagem pública não abre detalhe"
grep -q 'onOpen={openOccurrence}' "$HOME" || fail "listagem da Home não abre detalhe"
grep -q 'getPublicOccurrenceDetails' "$HOME" || fail "Home não carrega detalhe público"
grep -q 'PublicOccurrenceDetailsModal' "$HOME" || fail "Home não reutiliza modal público de ocorrência"
grep -q 'role="dialog"' "$MODAL" || fail "detalhe público não usa dialog acessível"
grep -q 'occurrence.media.map' "$MODAL" || fail "galeria completa não é renderizada"
grep -q '<video controls' "$MODAL" || fail "vídeos não são reproduzíveis no detalhe"
grep -q 'Fechar detalhes da ocorrência' "$MODAL" || fail "modal sem fechamento acessível"

echo "global_toast_notifications=OK"
echo "native_alerts_migrated_to_toast=OK"
echo "anonymous_support_toast=OK"
echo "occurrence_form_protocol_first=OK"
echo "occurrence_form_paired_fields_aligned=OK"
echo "occurrence_creation_master_required=OK"
echo "occurrence_creation_address_required=OK"
echo "occurrence_creation_protocol_required=OK"
echo "occurrence_creation_photo_required=OK"
echo "occurrence_creation_atomic_target=OK"
echo "occurrence_address_map_sync=OK"
echo "occurrence_required_markers_inline=OK"
echo "public_occurrence_cover_contract=OK"
echo "public_occurrence_ready_media_only=OK"
echo "public_occurrence_signed_media=OK"
echo "public_occurrence_first_photo_cover=OK"
echo "public_occurrence_public_protocol=OK"
echo "public_occurrence_support_count=OK"
echo "public_occurrence_support_button=OK"
echo "public_occurrence_row_click_only=OK"
echo "public_occurrence_support_inside_main=OK"
echo "public_occurrence_clickable_card=OK"
echo "public_occurrence_details_dialog=OK"
echo "public_occurrence_full_gallery=OK"
echo "home_occurrence_details=OK"
echo "PUBLIC OCCURRENCE DETAILS GUARD: OK"
