// <auto-generated />
using System;
using CidadeEmDia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CidadeEmDia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901190552_AddMercadoPagoBillingProvider")]
    partial class AddMercadoPagoBillingProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<DateTimeOffset?>("SignupFeePaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_fee_paid_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId")
                        .IsUnique();

                    b.ToTable("billing_customers", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAuthorizedPaymentId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("provider_authorized_payment_id");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetail")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("status_detail");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("Provider", "ProviderAuthorizedPaymentId");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingPaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("LiveMode")
                        .HasColumnType("boolean")
                        .HasColumnName("live_mode");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("processing_error");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resource_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique();

                    b.HasIndex("Provider", "Type", "ResourceId");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingProviderSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("checkout_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("external_reference");

                    b.Property<DateTimeOffset?>("FirstApprovedPaymentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_approved_payment_at");

                    b.Property<long>("InitialAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("initial_amount_cents");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderStatus")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("provider_status");

                    b.Property<string>("ProviderSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<long>("RecurringAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("recurring_amount_cents");

                    b.Property<DateTimeOffset?>("RecurringAmountSynchronizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recurring_amount_synchronized_at");

                    b.Property<bool>("SignupFeeIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("signup_fee_included");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalReference")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderSubscriptionId")
                        .IsUnique();

                    b.ToTable("billing_provider_subscriptions", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BillingIntervalMonths")
                        .HasColumnType("integer")
                        .HasColumnName("billing_interval_months");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("plan_categories", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PlanId", "CategoryId")
                        .IsUnique();

                    b.ToTable("plan_offers", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<long?>("MarketingReferencePriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("marketing_reference_price_cents");

                    b.Property<int>("MonthlyPublicationLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_publication_limit");

                    b.Property<Guid>("PlanOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_offer_id");

                    b.Property<long>("PriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("price_cents");

                    b.Property<long>("SignupFeeCents")
                        .HasColumnType("bigint")
                        .HasColumnName("signup_fee_cents");

                    b.Property<int>("SubaccountLimit")
                        .HasColumnType("integer")
                        .HasColumnName("subaccount_limit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PlanOfferId", "EffectiveFrom");

                    b.HasIndex("PlanOfferId", "Version")
                        .IsUnique();

                    b.ToTable("plan_versions", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<DateTimeOffset?>("GracePeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_ends_at");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<DateTimeOffset?>("PastDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("past_due_at");

                    b.Property<Guid?>("PendingPlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_plan_version_id");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_version_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPeriodEnd");

                    b.HasIndex("PendingPlanVersionId");

                    b.HasIndex("PlanVersionId");

                    b.HasIndex("MasterUserId", "Status");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.UsageCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PublicationCount")
                        .HasColumnType("integer")
                        .HasColumnName("publication_count");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "WindowStart")
                        .IsUnique();

                    b.ToTable("usage_counters", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CitizenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("citizen_user_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_id");

                    b.Property<Guid>("OccurrenceTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_target_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CitizenUserId");

                    b.HasIndex("MasterUserId");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("OccurrenceTargetId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("chat_conversations", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.HasIndex("ConversationId", "SenderUserId", "ClientMessageId")
                        .IsUnique();

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("chat_participants", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.MasterSubaccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubaccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subaccount_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubaccountUserId");

                    b.HasIndex("MasterUserId", "Status");

                    b.HasIndex("MasterUserId", "SubaccountUserId")
                        .IsUnique();

                    b.ToTable("master_subaccounts", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.MasterSubaccountPermission", b =>
                {
                    b.Property<Guid>("MasterSubaccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_subaccount_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("MasterSubaccountId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("master_subaccount_permissions", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.SubaccountInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PermissionKeysJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permission_keys_json");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("MasterUserId", "NormalizedEmail");

                    b.ToTable("subaccount_invitations", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_media_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Document")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_text");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalProtocolAgency")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_protocol_agency");

                    b.Property<string>("ExternalProtocolNumber")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("external_protocol_number");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postal_code");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("public_code");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_occurrences_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("PublicCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("occurrences", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status", "DisplayOrder");

                    b.ToTable("occurrence_categories", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ActualSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_size_bytes");

                    b.Property<DateTimeOffset?>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpectedSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size_bytes");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<Guid?>("OccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploaderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_occurrence_media_object_key");

                    b.HasIndex("OccurrenceId")
                        .HasDatabaseName("ix_occurrence_media_occurrence_id");

                    b.HasIndex("UploaderUserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_occurrence_media_uploader_status_created");

                    b.ToTable("occurrence_media", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId")
                        .HasDatabaseName("ix_occurrence_supports_occurrence_id");

                    b.HasIndex("UserId");

                    b.HasIndex("OccurrenceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_occurrence_supports_occurrence_user");

                    b.ToTable("occurrence_supports", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_user_id");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.HasIndex("MasterUserId", "Status");

                    b.HasIndex("OccurrenceId", "MasterUserId")
                        .IsUnique();

                    b.ToTable("occurrence_targets", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceTargetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByMasterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_master_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MasterSubaccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_subaccount_id");

                    b.Property<Guid>("OccurrenceTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("occurrence_target_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByMasterUserId");

                    b.HasIndex("MasterSubaccountId");

                    b.HasIndex("OccurrenceTargetId")
                        .IsUnique();

                    b.HasIndex("MasterSubaccountId", "AssignedAt");

                    b.ToTable("occurrence_target_assignments", (string)null);
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingCustomer", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingPayment", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Billing.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.BillingProviderSubscription", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Billing.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanOffer", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Billing.PlanCategory", "Category")
                        .WithMany("Offers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Billing.Plan", "Plan")
                        .WithMany("Offers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanVersion", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Billing.PlanOffer", "PlanOffer")
                        .WithMany("Versions")
                        .HasForeignKey("PlanOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanOffer");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.Subscription", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Billing.PlanVersion", "PendingPlanVersion")
                        .WithMany()
                        .HasForeignKey("PendingPlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CidadeEmDia.Domain.Billing.PlanVersion", "PlanVersion")
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterUser");

                    b.Navigation("PendingPlanVersion");

                    b.Navigation("PlanVersion");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.UsageCounter", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Billing.Subscription", "Subscription")
                        .WithMany("UsageCounters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatConversation", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CitizenUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Occurrences.OccurrenceTarget", null)
                        .WithOne()
                        .HasForeignKey("CidadeEmDia.Domain.Chat.ChatConversation", "OccurrenceTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatMessage", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Chat.ChatConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatParticipant", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Chat.ChatConversation", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.MasterSubaccount", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.User", "SubaccountUser")
                        .WithMany()
                        .HasForeignKey("SubaccountUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterUser");

                    b.Navigation("SubaccountUser");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.MasterSubaccountPermission", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.MasterSubaccount", "MasterSubaccount")
                        .WithMany("Permissions")
                        .HasForeignKey("MasterSubaccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterSubaccount");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.SubaccountInvitation", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.UserProfile", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("CidadeEmDia.Domain.Identity.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.Occurrence", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Occurrences.OccurrenceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("CidadeEmDia.Domain.Occurrences.OccurrenceComplement", "Complements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AuthorUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_user_id");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("content");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("OccurrenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("occurrence_id");

                            b1.HasKey("Id");

                            b1.HasIndex("AuthorUserId");

                            b1.HasIndex("OccurrenceId", "CreatedAt");

                            b1.ToTable("occurrence_complements", (string)null);

                            b1.HasOne("CidadeEmDia.Domain.Identity.User", null)
                                .WithMany()
                                .HasForeignKey("AuthorUserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("OccurrenceId");
                        });

                    b.OwnsMany("CidadeEmDia.Domain.Occurrences.OccurrenceServiceForecast", "ServiceForecastHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("DefinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("defined_at");

                            b1.Property<Guid>("DefinedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("defined_by_user_id");

                            b1.Property<DateTimeOffset>("EstimatedFor")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("estimated_for");

                            b1.Property<string>("Note")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("note");

                            b1.Property<Guid>("OccurrenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("occurrence_id");

                            b1.HasKey("Id");

                            b1.HasIndex("DefinedByUserId");

                            b1.HasIndex("OccurrenceId", "DefinedAt");

                            b1.ToTable("occurrence_service_forecasts", (string)null);

                            b1.HasOne("CidadeEmDia.Domain.Identity.User", null)
                                .WithMany()
                                .HasForeignKey("DefinedByUserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("OccurrenceId");
                        });

                    b.OwnsMany("CidadeEmDia.Domain.Occurrences.OccurrenceStatusChange", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ChangedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by_user_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("FromStatus")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("from_status");

                            b1.Property<Guid>("OccurrenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("occurrence_id");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("reason");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("to_status");

                            b1.HasKey("Id");

                            b1.HasIndex("ChangedByUserId");

                            b1.HasIndex("OccurrenceId", "CreatedAt");

                            b1.ToTable("occurrence_status_history", (string)null);

                            b1.HasOne("CidadeEmDia.Domain.Identity.User", null)
                                .WithMany()
                                .HasForeignKey("ChangedByUserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("OccurrenceId");
                        });

                    b.Navigation("Complements");

                    b.Navigation("ServiceForecastHistory");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceMedia", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Occurrences.Occurrence", null)
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceSupport", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Occurrences.Occurrence", null)
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceTarget", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Occurrences.Occurrence", "Occurrence")
                        .WithMany("Targets")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.OccurrenceTargetAssignment", b =>
                {
                    b.HasOne("CidadeEmDia.Domain.Identity.User", "AssignedByMasterUser")
                        .WithMany()
                        .HasForeignKey("AssignedByMasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Identity.MasterSubaccount", "MasterSubaccount")
                        .WithMany()
                        .HasForeignKey("MasterSubaccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidadeEmDia.Domain.Occurrences.OccurrenceTarget", "OccurrenceTarget")
                        .WithMany()
                        .HasForeignKey("OccurrenceTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByMasterUser");

                    b.Navigation("MasterSubaccount");

                    b.Navigation("OccurrenceTarget");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.Plan", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanCategory", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.PlanOffer", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Billing.Subscription", b =>
                {
                    b.Navigation("UsageCounters");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Chat.ChatConversation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.MasterSubaccount", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Identity.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CidadeEmDia.Domain.Occurrences.Occurrence", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
